### ISSUE TITLE
Image is not creating

### ISSUE THREAD

**Issue by menporulporiayalan** [mirrorkeydev/Visualizations#1]
Hi, 

I have generated the whatsapphistory python script. It seems working good but the graph .svg image is not exporting.

**Comment by mirrorkeydev** [comment]
Hi!
Can you give me a bit more information?
What is the error you are getting, which graph ( calc_freq_over_time() or calc_avg_texts_per_hour() ) are you trying to generate?

**Comment by menporulporiayalan** [comment]
@mirrorkeydev 

I uncommented the lines number 28 and 29 and I generated. I got the below error. 

```
File "whatsapphistory.py", line 314, in <module>
    main()
  File "whatsapphistory.py", line 28, in main
    calc_freq_over_time()
  File "whatsapphistory.py", line 89, in calc_freq_over_time
    fig.write_image("whatsappimages/frequencybyday.svg")
  File "/home/emperoreby/.local/lib/python3.7/site-packages/plotly/basedatatypes.py", line 2824, in write_image
    return pio.write_image(self, *args, **kwargs)
  File "/home/emperoreby/.local/lib/python3.7/site-packages/plotly/io/_orca.py", line 1767, in write_image
    fig, format=format, scale=scale, width=width, height=height, validate=validate
  File "/home/emperoreby/.local/lib/python3.7/site-packages/plotly/io/_orca.py", line 1532, in to_image
    ensure_server()
  File "/home/emperoreby/.local/lib/python3.7/site-packages/plotly/io/_orca.py", line 1390, in ensure_server
    validate_executable()
  File "/home/emperoreby/.local/lib/python3.7/site-packages/plotly/io/_orca.py", line 1206, in validate_executable
    executable=" ".join(executable_list), help_result=help_result
ValueError: 
The orca executable is required in order to export figures as static images,
but the executable that was found at '/usr/bin/orca'
does not seem to be a valid plotly orca executable. Please refer to the end of
this message for details on what went wrong.

```
As I don't have orca, I installed orca by the below command: 
`
npm install -g electron@6.1.4 orca`

Then, I generated the whatsapp script again and I got this below error: 

`[4298:0122/111623.577124:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
`

**Comment by mirrorkeydev** [comment]
I'm not sure what could be causing that error. The script runs fine for me on Python 3.7 (as I see you are using as well), with Windows 10. Preliminary Googling shows that error popping up in mainly Linux environments, including Debian, Fedora, Arch Linux, and Ubuntu environments using Spotify and Chrome. I'm inclined to think that this is an issue with your specific environment setup - is it possible you're using Linux?

I can't fix any issues that are caused by the dependencies of my script, sorry :(

**Comment by menporulporiayalan** [comment]
Yes, You are right. I am using  Ubuntu 19.10 and I am using chrome. The issue actually on the  `fig.write_image()`. I tried `fig.show()` it seems the graph is generated perfectly.

**Comment by mirrorkeydev** [comment]
Cool! I'm glad you were able to get the issue resolved :)

**Comment by menporulporiayalan** [comment]
I installed orca by the below comment and resolved my issue :)

`sudo npm install -g electron@1.8.4 orca `
