### ISSUE TITLE
How to generate this script properly?

### ISSUE THREAD

**Issue by menporulporiayalan** [mirrorkeydev/Visualizations#2]
Hi, 

I generated this "whatsapphistory.py" by the command `python whatsapphistory.py`, Is it a correct way to generate? Because I don't see any images generated according to your public [images](https://github.com/mirrorkeydev/Visualizations/blob/master/public/analysis.png). There are only two images generated in the whatsappimages folder which are **frequencybyday.svg** and **hourlytextsboth.svg**. 

Kindly direct me.

**Comment by mirrorkeydev** [comment]
Hi!

The image that you see - the final product - is the result of me compiling all of the data that the script generates by hand into an infographic using [Inkscape](https://inkscape.org/). Unfortunately, the script doesn't actually create the final image, it just creates the graphs in them and the command line will show you outputs for all of the other data contained in the infographic.

**Comment by menporulporiayalan** [comment]
Thank you @mirrorkeydev, Let me close this then.
